### ISSUE TITLE
Calendar not showing properly

### ISSUE THREAD

**Issue by tartesso26** [joshuaeasy/vue3-daterange-picker#3]
i can use vue3-daterange-picker, and it works, but, calendar don´t appear over the content, and appear without any style, i´m missing something??

i´m pretty sure it´s my fault not component but i don´t know where to ask

**Comment by tartesso26** [comment]
also properties documented in vue2 version are not valids in vue3 version

**Comment by joshuaeasy** [comment]
Hi @tartesso26 

You will need to import the CSS file to your SCSS or CSS whichever one you're using

`@import 'vue3-daterange-picker/src/assets/daterangepicker.scss';`

~ Josh
